
Insert into SEGURIDAD.SEG_M_TRANSACCIONES
   (PERS_EMPRESA_N_PK, 
    TRAN_IDTRANSACCION_N, TRAN_DESCRIPCION_V, TRAN_NOMBRE_V, TRAN_NIVEL_N, TRAN_ORDEN_N, 
    TRAN_TIPOMENU_N, TRAN_CRECIMIENTO_N, TRAN_TIPOTRANSACCION_N, TRAN_FINAL_N, TRAN_IDESTADO_N, 
    PERS_EMPRESAPADRE_N_PK, TRAN_IDTRANSACCIONPADRE_N, TRANS_FECHAELIMINACION_D, TRAN_MODULO_V, TRAN_PAGINA_V, 
    PERS_PERSONAELIMINA_N_PK)
 Values
   (2, 330, NULL, 'Liquidar Sesiones', 3, 
    2, 1, 2, NULL, 0, 
    1, 2, 7, NULL, '/SeguridadWeb', 
    '/pages/permiso/liquidatesesion/liquidateMain.jsf', NULL);

Insert into SEGURIDAD.SEG_V_PERFILDETALLE
   (PERS_EMPRESA_N_PK, 
    PERF_IDPERFIL_N, TRAN_IDTRANSACCION_N, PEDE_IDESTADO_N)
 Values
   (2, 22, 330, 1);
COMMIT;
