package pe.com.tumi.common.util;

public enum Columna {
	
	SP_EMPRESA(0), 
	SP_CORRELATIVO(1), 
	SP_FECHAREGISTRO(2), 
	SP_DOCUMENTOGENERAL(3),
	SP_SUBTIPO(4),
	SP_TIPOOPERACION(5),
	SP_PERSONA(6),
	SP_MONEDA(7),
	SP_MONTOTOTAL(8),
	SP_PERIODO(9),
	SP_TIPOPLANILLA(10),
	SP_TIPOPERIODO(11),
	SP_OBSERVACION(12),
	SP_ESTADO(13),
	SP_USUARIO(14),
	SP_ASIENTO(15),
	
	SPD_EMPRESA(0),
	SPD_CORRELATIVO(1),
	SPD_CORRELATIVODETALLE(2),
	SPD_DOCUMENTOGENERAL(3),
	SPD_EMPRESAPERSONA(4),
	SPD_PERSONA(5),
	SPD_MONEDA(6),
	SPD_MONTOTOTAL(7),
	SPD_SUCURSAL(8),
	SPD_SUBSUCURSAL(9),
	SPD_AREA(10),
	SPD_EMPRESAPLANCUENTA(11),
	SPD_PERIODOPLANCUENTA(12),
	SPD_NUMEROPLANCUENTA(13),
	SPD_DEBEHABER(14),
	SPD_NUMERODOCUMENTO(15),
	
	SPP_EMPRESA(0),
	SPP_CORRELATIVO(1),
	SPP_CORRELATIVOPAGO(2),
	SPP_EMPRESAEGRESO(3),
	SPP_ITEMEGRESO(4),
	SPP_MONTO(5),
	SPP_ESTADO(6);
	
	private int valor;
	 
	private Columna(int valor) {
		this.valor = valor;
	}
	 
	public int getValor() {
		return valor;
	}
}