
-----SOLO MODIFICAR EL SGTE SP-------------
PROCEDURE getPorEmpresaYPeriodo (
   V_LISTA                        OUT cursorLista,
   V_CONT_PERIODOCUENTA_N         IN  CON_PLANCUENTA.CONT_PERIODOCUENTA_N%TYPE,
   V_PERS_EMPRESACUENTA_N_PK      IN  CON_PLANCUENTA.PERS_EMPRESACUENTA_N_PK%TYPE
   )
IS
    var_lista   cursorLista;
BEGIN
    OPEN var_lista FOR
    SELECT
          PERS_EMPRESACUENTA_N_PK      pPERS_EMPRESACUENTA_N_PK,
          CONT_PERIODOCUENTA_N        pCONT_PERIODOCUENTA_N,
          CONT_NUMEROCUENTA_V          pCONT_NUMEROCUENTA_V,
          PERS_EMPRESAORIGEN_N_PK      pPERS_EMPRESAORIGEN_N_PK,
          CONT_PERIODOORIGEN_N        pCONT_PERIODOORIGEN_N,
          CONT_NUMEROCUENTAORIGEN_V    pCONT_NUMEROCUENTAORIGEN_V,
          PERS_EMPRESADESTINO_N_PK    pPERS_EMPRESADESTINO_N_PK,
          CONT_PERIODODESTINO_N        pCONT_PERIODODESTINO_N,
          CONT_NUMEROCUENTADESTINO_V  pCONT_NUMEROCUENTADESTINO_V,
          PLCU_DESCRIPCION_V          pPLCU_DESCRIPCION_V,
          PLCU_COMENTARIO_V                   pPLCU_COMENTARIO_V,
          PLCU_MOVIMIENTO_N                   pPLCU_MOVIMIENTO_N,
          PLCU_IDENTIFICADOREXTRANJERO_N     pPLCU_IDENTIFICADOREXT_N,
          PLCU_FECHAREGISTRO_D               pPLCU_FECHAREGISTRO_D,
          PERS_EMPRESAUSUARIO_N_PK           pPERS_EMPRESAUSUARIO_N_PK,
          PERS_PERSONAUSUARIO_N_PK           pPERS_PERSONAUSUARIO_N_PK,
          PARA_ESTADO_N_COD                   pPARA_ESTADO_N_COD,
          PLCU_FECHAELIMINACION_D             pPLCU_FECHAELIMINACION_D,
         PERS_EMPRESAELIMINAR_N_PK          pPERS_EMPRESAELIMINAR_N_PK,
         PERS_PERSONAELIMINAR_N_PK          pPERS_PERSONAELIMINAR_N_PK
     FROM
         CON_PLANCUENTA
     WHERE
         CONT_PERIODOCUENTA_N      = V_CONT_PERIODOCUENTA_N AND
         PERS_EMPRESACUENTA_N_PK   = V_PERS_EMPRESACUENTA_N_PK
         --Inicio: REQ14-004 - bizarq - 27/09/2014
         AND PARA_ESTADO_N_COD = PKG_CONSTANTE.C_ESTADO_ACTIVO
         ORDER BY 3
         --Fin: REQ14-004 - bizarq - 27/09/2014
         --AND CONT_NUMEROCUENTA_V IN ('1113','1111')
         ;
    V_LISTA := var_lista;
END getPorEmpresaYPeriodo;