--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, PERS_EMPRESA_N_PK, TRAN_IDTRANSACCION_N, TRAN_DESCRIPCION_V, 
--     TRAN_NOMBRE_V, TRAN_NIVEL_N, TRAN_ORDEN_N, 
--     TRAN_TIPOMENU_N, TRAN_CRECIMIENTO_N, TRAN_TIPOTRANSACCION_N, 
--     TRAN_FINAL_N, TRAN_IDESTADO_N, PERS_EMPRESAPADRE_N_PK, 
--     TRAN_IDTRANSACCIONPADRE_N, TRANS_FECHAELIMINACION_D, TRAN_MODULO_V, 
--     TRAN_PAGINA_V, PERS_PERSONAELIMINA_N_PK
--  FROM SEGURIDAD.SEG_M_TRANSACCIONES
--  Where
--  TRAN_IDTRANSACCION_N in ( 331,332,333)
--
Insert into SEGURIDAD.SEG_M_TRANSACCIONES
   (PERS_EMPRESA_N_PK, 
    TRAN_IDTRANSACCION_N, TRAN_DESCRIPCION_V, TRAN_NOMBRE_V, TRAN_NIVEL_N, TRAN_ORDEN_N, 
    TRAN_TIPOMENU_N, TRAN_CRECIMIENTO_N, TRAN_TIPOTRANSACCION_N, TRAN_FINAL_N, TRAN_IDESTADO_N, 
    PERS_EMPRESAPADRE_N_PK, TRAN_IDTRANSACCIONPADRE_N, TRANS_FECHAELIMINACION_D, TRAN_MODULO_V, TRAN_PAGINA_V, 
    PERS_PERSONAELIMINA_N_PK)
 Values
   (2, 331, NULL, 'Tesoreria', 2, 
    3, 1, 2, NULL, 0, 
    1, 2, 118, NULL, NULL, 
    NULL, NULL);
Insert into SEGURIDAD.SEG_M_TRANSACCIONES
   (PERS_EMPRESA_N_PK, 
    TRAN_IDTRANSACCION_N, TRAN_DESCRIPCION_V, TRAN_NOMBRE_V, TRAN_NIVEL_N, TRAN_ORDEN_N, 
    TRAN_TIPOMENU_N, TRAN_CRECIMIENTO_N, TRAN_TIPOTRANSACCION_N, TRAN_FINAL_N, TRAN_IDESTADO_N, 
    PERS_EMPRESAPADRE_N_PK, TRAN_IDTRANSACCIONPADRE_N, TRANS_FECHAELIMINACION_D, TRAN_MODULO_V, TRAN_PAGINA_V, 
    PERS_PERSONAELIMINA_N_PK)
 Values
   (2, 332, NULL, 'Fondos fijos', 3, 
    1, 1, 2, NULL, 0, 
    1, 2, 331, NULL, NULL, 
    NULL, NULL);
Insert into SEGURIDAD.SEG_M_TRANSACCIONES
   (PERS_EMPRESA_N_PK, 
    TRAN_IDTRANSACCION_N, TRAN_DESCRIPCION_V, TRAN_NOMBRE_V, TRAN_NIVEL_N, TRAN_ORDEN_N, 
    TRAN_TIPOMENU_N, TRAN_CRECIMIENTO_N, TRAN_TIPOTRANSACCION_N, TRAN_FINAL_N, TRAN_IDESTADO_N, 
    PERS_EMPRESAPADRE_N_PK, TRAN_IDTRANSACCIONPADRE_N, TRANS_FECHAELIMINACION_D, TRAN_MODULO_V, TRAN_PAGINA_V, 
    PERS_PERSONAELIMINA_N_PK)
 Values
   (2, 333, NULL, 'Ingresos', 3, 
    2, 1, 2, NULL, 0, 
    1, 2, 331, NULL, '/ReporteWeb', 
    '/pages/tesoreria/ingresos/ingresos.jsf', NULL);
COMMIT;
